FROM python:3.8.3-buster

# COPY ../requirements.txt  /requirements.txt 

# RUN pip3 install -r /requirements.txt

RUN python3 -m pip install --upgrade pip
# RUN pip3 install --upgrade git+https://github.com/m-wrzr/populartimes


WORKDIR /api
